# run this file in the napari-env
# use this to open the fiducial_max_projection.ome_seg.npy file in qi2labdatastore/segmentation/cellpose
# The numpy file cannot be dragged and dropped into Napari. 

# If your .npy file was generated by software like Cellpose, it might actually be a pickled Python dictionary instead of a raw image array.
# Opening these directly via drag-and-drop will throw a ReaderPluginError or a pickle flag error.
# You will need to load them via Python code using np.load('file.npy', allow_pickle=True).item() to unpack the numerical array first.

# Cellpose .npy outputs are dictionaries.
# The actual multi-dimensional pixel data is stored under the 'masks' key.
# The code now extracts cellpose_data['masks'] before handing it to napari.

import argparse
import napari
import numpy as np

# Get the Zarr path from the command line.
parser = argparse.ArgumentParser(
    description=""
)   
parser.add_argument(
    "path",
    help="Add absolute path to CellPose masks as npy. Cannot be a directory",
)
args = parser.parse_args()

# 1. Load the dictionary and extract the masks array
cellpose_data = np.load(args.path, allow_pickle=True).item()
masks_array = cellpose_data['masks']  # Cellpose stores the segmentation array under the 'masks' key

viewer = napari.Viewer()

# # 2. Open the OME-Zarr file using the command-line variable
# viewer.open(args.zarr_path)

# 3. Add the masks as a LABELS layer (not an image layer)
viewer.add_labels(masks_array, name='Cellpose Masks')

napari.run()
